version: 2.0.{build}
image: Visual Studio 2019
environment:
  CLI_VERSION: 2.0.0
  MYGET_API_KEY:
    secure: dtTGYQHgEupz5SmTDFkvDW1uEZH7mEM8PD948uzOZY/XCl965mhorbEl2e+6U8pO
  NUGET_API_KEY:
    secure: vHyIVcDhnuRFDr1TY74oVztAv37sgzMxULqrC1OXkysQEBgBSpBjXsuc0jnyz775

configuration: Release

build_script:
- cmd: msbuild /m /restore /t:Build;Pack /v:minimal SharpGen.Runtime.COM.sln

artifacts:
- path: '**/*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: vHyIVcDhnuRFDr1TY74oVztAv37sgzMxULqrC1OXkysQEBgBSpBjXsuc0jnyz775
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://www.myget.org/F/sharpgentools/api/v2/package
  api_key:
    secure: dtTGYQHgEupz5SmTDFkvDW1uEZH7mEM8PD948uzOZY/XCl965mhorbEl2e+6U8pO
  on:
    branch: master
    APPVEYOR_REPO_TAG: false
