version: 2.0.{build}
image: Visual Studio 2019 Preview
environment:
  CLI_VERSION: 2.0.0
  MYGET_API_KEY:
    secure: dtTGYQHgEupz5SmTDFkvDW1uEZH7mEM8PD948uzOZY/XCl965mhorbEl2e+6U8pO
  NUGET_API_KEY:
    secure: 4WMsxFFj1s1R+uO8E96HqveIJM77lMWjcWhUnfpXslepnAMlPVigu/SPKnd4aCQn

configuration: Release

build_script:
- cmd: msbuild /m /restore /t:Build;Pack /v:minimal

artifacts:
- path: '**/*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: YllGn/UU5leb3rTBzsuJ/fBlD76dAnZ+V0OGI+AnptcdAUe5i9LqOsaz2VaL0kxo
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://www.myget.org/F/sharpgentools/api/v2/package
  api_key:
    secure: dtTGYQHgEupz5SmTDFkvDW1uEZH7mEM8PD948uzOZY/XCl965mhorbEl2e+6U8pO
  on:
    branch: master
    APPVEYOR_REPO_TAG: false
